### ISSUE TITLE
按照文档部署后群指令功能可以使用, 但是私聊功能有问题。

### ISSUE THREAD

**Issue by yyz940922** [LQBing/YoshinoBotDeploy#2]
比如我想改密码, 私聊机器人后的日志。

```sh
[2020-08-20 09:37:34,788 nonebot] INFO: Self: 3237573816, Message 18307 from 591806780: '登录'
Task exception was never retrieved
future: <Task finished name='Task-523' coro=<CQHttp._handle_event_with_response() done, defined at /usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py:581> cal/lib/python3.8/asyncio/tasks.py:382>
source_traceback: Object created at (most recent call last):
  File "run.py", line 8, in <module>
    bot.run(use_reloader=False, loop=asyncio.get_event_loop())
  File "/usr/local/lib/python3.8/site-packages/nonebot/__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 210, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1621, in run
    loop.run_until_complete(task)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/quart/asgi.py", line 151, in handle_websocket
    response = await self.app.handle_websocket(websocket)
  File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1928, in handle_websocket
    return await self.full_dispatch_websocket(websocket_context)
  File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1948, in full_dispatch_websocket
    result = await self.dispatch_websocket(websocket_context)
  File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1993, in dispatch_websocket
    return await handler(**websocket_.view_args)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 501, in _handle_wsr
    await self._handle_wsr_universal()
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 545, in _handle_wsr_universal
    asyncio.create_task(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 382, in create_task
    task = loop.create_task(coro)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 583, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 577, in _handle_event
    await self._bus.emit(event_name, ev)))
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/bus.py", line 57, in emit
    results += await run_async_funcs(self._subscribers[event],
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/utils.py", line 41, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "/workdir/hoshino/service.py", line 186, in wrapper
    if self._check_all(ctx):
  File "/workdir/hoshino/service.py", line 163, in _check_all
    return self.check_enabled(gid) and not priv.check_block_group(gid) and priv.check_priv(ev, self.use_priv)
  File "/workdir/hoshino/priv.py", line 76, in check_priv
    return hoshino.config.bot_manager_web.ALLOW_PRIVATE
AttributeError: module 'hoshino.config' has no attribute 'bot_manager_web'
[2020-08-20 09:37:34,794 nonebot] DEBUG: Parsing command: '登录'
[2020-08-20 09:37:34,794 nonebot] DEBUG: Matched command start: (empty)
[2020-08-20 09:37:34,797 nonebot] DEBUG: Split command name: ('登录',)
[2020-08-20 09:37:34,797 nonebot] DEBUG: Command ('登录',) not found. Try to match aliases
[2020-08-20 09:37:34,797 nonebot] DEBUG: Not a known command, ignored

```

- 报错说hoshine.config目录下没有bot_manager_web属性

调度也有报错(说少了个json)

```sh
[2020-08-20 09:45:25,071 pcr-comic] INFO: Scheduled job update_seeker start.
[2020-08-20 09:45:25,072 pcr-comic] ERROR: <class 'FileNotFoundError'> occured when doing scheduled job update_seeker.
[2020-08-20 09:45:25,072 pcr-comic] ERROR: [Errno 2] No such file or directory: './res/img/priconne/comic/index.json'
Traceback (most recent call last):
  File "/workdir/hoshino/service.py", line 337, in wrapper
    ret = await func()
  File "/workdir/hoshino/modules/priconne/comic.py", line 109, in update_seeker
    index = load_index()
  File "/workdir/hoshino/modules/priconne/comic.py", line 23, in load_index
    with open(R.get('img/priconne/comic/index.json').path, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './res/img/priconne/comic/index.json'
```

**Comment by yyz940922** [comment]
通过.env配置的mysql数据库是在容器中的么? 为什么我在容器中找不到mysql的进程? 配了本地的mysql重启后也没有初始化数据库。 @LQBing

**Comment by LQBing** [comment]
ALLOW_PRIVATE的问题修复了。重新pull 一下image就可以。
DB是之前尝试改成mysql，后来想了想弄那么重不太好，就继续维持原状了，只是.env忘记删了。
另外，我在里面用的是自己的简单授权验证，不能独立运行，我要想想怎么移除。

**Comment by LQBing** [comment]
刚刚更新了image，auth_inspect默认关闭，我有空想想看怎么换掉授权组件吧。
